# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f922981058ca96df946805a74f3a32a95749f5d1506829ffdcdb3c8a8a817be1e4f0ef77fe60e7c3435e22c493172e15abf380be0c856502b07bce5689fc8d40

test:
  secret_key_base: 1b3b5904758bd9de6678eb2778bab31019b8e81c1a91c2bb2324ad538678b21d8d82911f615a114de1f0fd36dbe081ec459bedbd2fdb1bc936fe0b3950a2bb1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
